### ISSUE TITLE
Cannot read property 'input' of undefined

### ISSUE THREAD

**Issue by maheshsetti** [vinothbabu/excel-to-json#1]
/lib/index.js:11
  if(!config.trans.input) {
                  ^
TypeError: Cannot read property 'input' of undefined

**Comment by vinothbabu** [comment]
can you share me your config.json which you are using? It seems you are trying to run without an input file...

**Comment by maheshsetti** [comment]
now i configured again, 

this is my config.json
path: json/config.json
{
  "name": "json",
  "version": "0.0.0",
  "description": "",
  "trans": {
    "input": "sample-file1.xls",
    "output": "output/"
  }
}

this time i didnt get any errors but it is not generating any output

json is my project name.

**Comment by vinothbabu** [comment]
Can you share me your code, so that i can see what's missing in it? It should create a sample-file1.json in your output folder... , i guess something is failing silently.

**Comment by piotrratajczak** [comment]
Have the same error. Did you find any solution?

**Comment by vinothbabu** [comment]
@piotrratajczak the error is because there is no input being passed from your end to generate the output. check what is your input.
