### ISSUE TITLE
File not convert into Json

### ISSUE THREAD

**Issue by Muhammadmateen** [vinothbabu/excel-to-json#2]
when ever i request this api it always show an error that
" Cannot read property 'input' of undefined".
please check this .....

**Comment by vinothbabu** [comment]
It means you are not passing any input... Check your input file

**Comment by creativefull** [comment]
yes i get same error this issue ,..

then for fix i'm using module xlsx-to-json 

https://github.com/creativefull/node-xlsx-json

**Comment by vinothbabu** [comment]
@creativefull : you need to pass an input file... could you provide more stack trace on this...

**Comment by creativefull** [comment]
i already pass an input file ,.. but i got error " Cannot read property 'input' of undefined".

**Comment by vinothbabu** [comment]
@creativefull : will it be possible to share the code.... i would like to see... the input on how are you passing... are you passing something like this `{
    input: "yourfilename",  // input directory 
    output: "output" // output directory 
   }`

**Comment by creativefull** [comment]
this is my code

```
excel2json({
   input: "./tmp/users.xlsx",
   output: null
}, function (err, result) {

});
```

**Comment by yusuf-multhan** [comment]
@creativefull Can you try with this change

```
excel2json({
    trans:{
        input: "input",
        output: "output"
   }
}, function (err, result) {
    if(err)console.log(err);
});
```

this issue has been fixed, actually we are missing trans key in config object @vinothbabu
